name: AWS
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 45

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/kaalmous/ngrok-rdp/kaal/resources/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/kaalmous/ngrok-rdp/kaal/resources/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/kaalmous/ngrok-rdp/kaal/resources/winrar.exe -OutFile winrar.exe
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/b1.bat -OutFile b1.bat
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/b2.bat -OutFile b2.bat
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/WebDriver.dll -OutFile WebDriver.dll
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/chromedriver.exe -OutFile chromedriver.exe
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/b5.ps1 -OutFile b5.ps1
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/b4.bat -OutFile b4.bat 
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/b9.bat -OutFile b9.bat


    - name: Extract ngrok Files
      run: Expand-Archive ngrok.zip

    - name: Connecting ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        copy winrar.exe C:\Users\Public\Desktop\winrar.exe
        copy b2.bat C:\Users\Public\Desktop\b2.bat
        copy b1.bat C:\Users\Public\Desktop\b1.bat
        copy b5.ps1 C:\Users\Public\Desktop\b5.ps1
        copy b4.bat C:\Users\Public\Desktop\b4.bat
        copy b9.bat C:\Users\Public\Desktop\b9.bat
        copy WebDriver.dll C:\Users\Public\Desktop\WebDriver.dll
        copy chromedriver.exe C:\Users\Public\Desktop\chromedriver.exe
       
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

    - name: Connect to RDP  [CPU 2 Core - 7GB Ram - 256 SSD]
      run: cmd /c start.bat

    - name: Install Winrar
      run: cmd /c C:\Users\Public\Desktop\winrar.exe winrar.exe /s

    - name: Set time
      run: cmd /c C:\Users\Public\Desktop\b1.bat

    - name: RUN BOT
      run: cmd /c C:\Users\Public\Desktop\b4.bat

    - name: RUN LOOP
      run: cmd /c C:\Users\Public\Desktop\b9.bat
     
    - name: TimeCount
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/adtitas/ngrok-rdp/main/resources/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
